[tool.pylint.main]
# Python code to execute, usually for sys.path manipulation such as
# pygtk.require().
init-hook = "import sys; sys.path.append('.')"

# A comma-separated list of package or module names from where C extensions may
# be loaded. Extensions are loading into the active Python interpreter and may
# run arbitrary code. (This is an alternative name to extension-pkg-allow-list
# for backward compatibility.)
extension-pkg-whitelist = ["pydantic"]

[tool.pylint."messages control"]
# Disable (messages, report, category, checker) by a list of the given ID(s).  
# You can also "--disable=all" and re"--enable=..." specific ones.  
# E.g: similarities, classes, W- for the corresponding classes or 
# warning category messages. 

disable = [ # User Defined
    "missing-final-newline", 
    "missing-function-docstring", "missing-module-docstring",
    "non-ascii-module-import", "non-ascii-name", 
    "superfluous-parens", "trailing-whitespace", "trailing-newlines",
    "unnecessary-lambda-assignment", 
    "use-dict-literal"]
